name:                lambda-launcher
version:             0.1.0.0
github:              "fabfianda/lambda-launcher"
license:             BSD3
author:              "Fabrizio Fiandanese"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fabfianda/lambda-launcher#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- shh
- text
- witch
- parsec
- utf8-string
- prettyprinter
- optparse-applicative
- transformers
- mtl
- exceptions


library:
  source-dirs: src

executables:
  lambda-launcher-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-launcher

tests:
  lambda-launcher-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-launcher
